// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EstateAgency.EF.Migrations;

/// <inheritdoc />
public partial class InitialCreate : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Clients",
            columns: table => new
            {
                Id = table.Column<int>(type: "int", nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                FullName = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                PassportNumber = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                PhoneNumber = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Clients", x => x.Id);
            });

        migrationBuilder.CreateTable(
            name: "Properties",
            columns: table => new
            {
                Id = table.Column<int>(type: "int", nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                Type = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                Purpose = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                CadastralNumber = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                Address = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: false),
                Floors = table.Column<int>(type: "int", nullable: false),
                TotalArea = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                Rooms = table.Column<int>(type: "int", nullable: false),
                CeilingHeight = table.Column<decimal>(type: "decimal(5,2)", nullable: true),
                Floor = table.Column<int>(type: "int", nullable: true),
                HasEncumbrances = table.Column<bool>(type: "bit", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Properties", x => x.Id);
            });

        migrationBuilder.CreateTable(
            name: "Requests",
            columns: table => new
            {
                Id = table.Column<int>(type: "int", nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                ClientId = table.Column<int>(type: "int", nullable: false),
                PropertyId = table.Column<int>(type: "int", nullable: false),
                Type = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                Amount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Requests", x => x.Id);
                table.ForeignKey(
                    name: "FK_Requests_Clients_ClientId",
                    column: x => x.ClientId,
                    principalTable: "Clients",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Restrict);
                table.ForeignKey(
                    name: "FK_Requests_Properties_PropertyId",
                    column: x => x.PropertyId,
                    principalTable: "Properties",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.CreateIndex(
            name: "IX_Clients_PassportNumber",
            table: "Clients",
            column: "PassportNumber",
            unique: true);

        migrationBuilder.CreateIndex(
            name: "IX_Properties_CadastralNumber",
            table: "Properties",
            column: "CadastralNumber",
            unique: true);

        migrationBuilder.CreateIndex(
            name: "IX_Requests_ClientId",
            table: "Requests",
            column: "ClientId");

        migrationBuilder.CreateIndex(
            name: "IX_Requests_PropertyId",
            table: "Requests",
            column: "PropertyId");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "Requests");

        migrationBuilder.DropTable(
            name: "Clients");

        migrationBuilder.DropTable(
            name: "Properties");
    }
}
